version: '3.5'
networks:
  traintiming_net:
    driver: bridge

services:
  traintiming.api:
    image: traintiming.api
    container_name: traintiming.api
    build:
      context: .
      dockerfile: TrainTiming.API/Dockerfile
    ports:
      - 5000:5000
    networks:
      - traintiming_net
    depends_on:
      - traintiming_db
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=host=postgres-container;port=5432;database=CoffeeMachine;Username=postgres;Password=toor;
      - KeycloakUrl=http://keycloak:8080
        
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://coffeemachine_db:5432/Keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: toor
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - coffeemachine_net
    ports:
      - 8282:8080
    depends_on:
      - coffeemachine_db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  traintiming_db:
    container_name: postgres-container
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: TrainTiming
    ports:
      - "7654:5432"
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      traintiming_net:
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data: